-- MySQL Script generated by MySQL Workbench
-- Wed Oct  6 18:31:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Vesolovskiy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Vesolovskiy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Vesolovskiy` DEFAULT CHARACTER SET utf8 ;
USE `Vesolovskiy` ;

-- -----------------------------------------------------
-- Table `Vesolovskiy`.`pizza_composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`pizza_composition` (
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`additives_for_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`additives_for_pizza` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `callories` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`pizza` (
  `id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `price` INT NOT NULL,
  `callories` VARCHAR(45) NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `additives` VARCHAR(45) NOT NULL,
  `composition` VARCHAR(45) NOT NULL,
  `number` INT NULL,
  `size` VARCHAR(10) NULL,
  `pizza_composition_name` VARCHAR(30) NOT NULL,
  `additives_for_pizza_idadditives for pizza` INT NOT NULL,
  PRIMARY KEY (`id`, `pizza_composition_name`, `additives_for_pizza_idadditives for pizza`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pizza_pizza composition1_idx` (`pizza_composition_name` ASC) VISIBLE,
  INDEX `fk_pizza_additives for pizza1_idx` (`additives_for_pizza_idadditives for pizza` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_pizza composition1`
    FOREIGN KEY (`pizza_composition_name`)
    REFERENCES `Vesolovskiy`.`pizza_composition` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_additives for pizza1`
    FOREIGN KEY (`additives_for_pizza_idadditives for pizza`)
    REFERENCES `Vesolovskiy`.`additives_for_pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`salad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`salad` (
  `id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `price` INT NOT NULL,
  `callories` VARCHAR(45) NULL,
  `composition` VARCHAR(95) NOT NULL,
  `weight` VARCHAR(10) NULL,
  `number` INT NOT NULL,
  `availability` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`drink` (
  `id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `size` VARCHAR(20) NOT NULL,
  `number` INT NOT NULL,
  `price` INT NOT NULL,
  `availability` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`courier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`courier` (
  `id` INT NOT NULL,
  `location` VARCHAR(35) NOT NULL,
  `name` VARCHAR(35) NOT NULL,
  `transport` VARCHAR(15) NOT NULL,
  `fulfilled_the_order` INT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`city` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`delivery` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `availability` VARCHAR(25) NOT NULL,
  `number` INT NOT NULL,
  `time` INT NULL,
  `order_status` VARCHAR(15) NULL,
  `discount` VARCHAR(45) NULL,
  `work_schedule` VARCHAR(35) NULL,
  `delivery_time` INT NULL,
  `payment_method` VARCHAR(15) NULL,
  `city_name` VARCHAR(20) NOT NULL,
  `pizza_id` INT NOT NULL,
  `pizza_pizza_composition_name` VARCHAR(30) NOT NULL,
  `pizza_additives_for_pizza_id` INT NOT NULL,
  `drink_id` INT NOT NULL,
  `salad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `city_name`, `pizza_id`, `pizza_pizza_composition_name`, `pizza_additives_for_pizza_id`, `drink_id`, `salad_id`),
  INDEX `fk_delivery_city1_idx` (`city_name` ASC) VISIBLE,
  INDEX `fk_delivery_pizza1_idx` (`pizza_id` ASC, `pizza_pizza_composition_name` ASC, `pizza_additives_for_pizza_id` ASC) VISIBLE,
  INDEX `fk_delivery_drink1_idx` (`drink_id` ASC) VISIBLE,
  INDEX `fk_delivery_salad1_idx` (`salad_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_city1`
    FOREIGN KEY (`city_name`)
    REFERENCES `Vesolovskiy`.`city` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_pizza1`
    FOREIGN KEY (`pizza_id` , `pizza_pizza_composition_name` , `pizza_additives_for_pizza_id`)
    REFERENCES `Vesolovskiy`.`pizza` (`id` , `pizza_composition_name` , `additives_for_pizza_idadditives for pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_drink1`
    FOREIGN KEY (`drink_id`)
    REFERENCES `Vesolovskiy`.`drink` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_salad1`
    FOREIGN KEY (`salad_id`)
    REFERENCES `Vesolovskiy`.`salad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`city` (
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`street`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`street` (
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`client` (
  `id` INT NOT NULL,
  `name` VARCHAR(25) NULL,
  `number` VARCHAR(15) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `payment for delivery` VARCHAR(10) NULL,
  `city_name` VARCHAR(30) NOT NULL,
  `street_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`, `city_name`, `street_name`),
  INDEX `fk_client_city1_idx` (`city_name` ASC) VISIBLE,
  INDEX `fk_client_street1_idx` (`street_name` ASC) VISIBLE,
  CONSTRAINT `fk_client_city1`
    FOREIGN KEY (`city_name`)
    REFERENCES `Vesolovskiy`.`city` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_street1`
    FOREIGN KEY (`street_name`)
    REFERENCES `Vesolovskiy`.`street` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`delivery_has_courier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`delivery_has_courier` (
  `delivery_id` INT NOT NULL,
  `delivery_city_name` VARCHAR(20) NOT NULL,
  `delivery_pizza_id` INT NOT NULL,
  `delivery_pizza_pizza composition_name` VARCHAR(30) NOT NULL,
  `delivery_pizza_additives for pizza_idadditives for pizza` INT NOT NULL,
  `delivery_drink_id` INT NOT NULL,
  `delivery_salad_id` INT NOT NULL,
  `courier_id` INT NOT NULL,
  `id` INT NOT NULL,
  INDEX `fk_delivery_has_courier_courier1_idx` (`courier_id` ASC) VISIBLE,
  INDEX `fk_delivery_has_courier_delivery1_idx` (`delivery_id` ASC, `delivery_city_name` ASC, `delivery_pizza_id` ASC, `delivery_pizza_pizza composition_name` ASC, `delivery_pizza_additives for pizza_idadditives for pizza` ASC, `delivery_drink_id` ASC, `delivery_salad_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_delivery_has_courier_delivery1`
    FOREIGN KEY (`delivery_id` , `delivery_city_name` , `delivery_pizza_id` , `delivery_pizza_pizza composition_name` , `delivery_pizza_additives for pizza_idadditives for pizza` , `delivery_drink_id` , `delivery_salad_id`)
    REFERENCES `Vesolovskiy`.`delivery` (`id` , `city_name` , `pizza_id` , `pizza_pizza_composition_name` , `pizza_additives_for_pizza_id` , `drink_id` , `salad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_has_courier_courier1`
    FOREIGN KEY (`courier_id`)
    REFERENCES `Vesolovskiy`.`courier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vesolovskiy`.`delivery_has_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vesolovskiy`.`delivery_has_client` (
  `client_id` INT NOT NULL,
  `client_city_name` VARCHAR(30) NOT NULL,
  `client_street_name` VARCHAR(30) NOT NULL,
  `delivery_id` INT NOT NULL,
  `delivery_city_name` VARCHAR(20) NOT NULL,
  `delivery_pizza_id` INT NOT NULL,
  `delivery_pizza_pizza composition_name` VARCHAR(30) NOT NULL,
  `delivery_pizza_additives for pizza_idadditives for pizza` INT NOT NULL,
  `delivery_drink_id` INT NOT NULL,
  `delivery_salad_id` INT NOT NULL,
  `id` INT NOT NULL,
  INDEX `fk_client_has_delivery_delivery1_idx` (`delivery_id` ASC, `delivery_city_name` ASC, `delivery_pizza_id` ASC, `delivery_pizza_pizza composition_name` ASC, `delivery_pizza_additives for pizza_idadditives for pizza` ASC, `delivery_drink_id` ASC, `delivery_salad_id` ASC) VISIBLE,
  INDEX `fk_client_has_delivery_client1_idx` (`client_id` ASC, `client_city_name` ASC, `client_street_name` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_has_delivery_client1`
    FOREIGN KEY (`client_id` , `client_city_name` , `client_street_name`)
    REFERENCES `Vesolovskiy`.`client` (`id` , `city_name` , `street_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_delivery_delivery1`
    FOREIGN KEY (`delivery_id` , `delivery_city_name` , `delivery_pizza_id` , `delivery_pizza_pizza composition_name` , `delivery_pizza_additives for pizza_idadditives for pizza` , `delivery_drink_id` , `delivery_salad_id`)
    REFERENCES `Vesolovskiy`.`delivery` (`id` , `city_name` , `pizza_id` , `pizza_pizza_composition_name` , `pizza_additives_for_pizza_id` , `drink_id` , `salad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
